// Code generated by generate-tl-files; DO NOT EDIT.

package telegram

type AccessPointRule struct {
	PhonePrefixRules string   `validate:"required"`
	DcId             int32    `validate:"required"`
	Ips              []IpPort `validate:"required"`
}

func (*AccessPointRule) CRC() uint32 {
	return uint32(0x4679b65f)
}

type AccountAuthorizationForm struct {
	// flags position
	RequiredTypes    []SecureRequiredType `validate:"required"`
	Values           []*SecureValue       `validate:"required"`
	Errors           []SecureValueError   `validate:"required"`
	Users            []User               `validate:"required"`
	PrivacyPolicyUrl string               `tl:"flag:0"`
}

func (*AccountAuthorizationForm) CRC() uint32 {
	return uint32(0xad2e1cd8)
}

type AccountAuthorizations struct {
	Authorizations []*Authorization `validate:"required"`
}

func (*AccountAuthorizations) CRC() uint32 {
	return uint32(0x1250abde)
}

type AccountAutoDownloadSettings struct {
	Low    *AutoDownloadSettings `validate:"required"`
	Medium *AutoDownloadSettings `validate:"required"`
	High   *AutoDownloadSettings `validate:"required"`
}

func (*AccountAutoDownloadSettings) CRC() uint32 {
	return uint32(0x63cacf26)
}

type AccountContentSettings struct {
	// flags position
	SensitiveEnabled   bool `tl:"flag:0,encoded_in_bitflag"`
	SensitiveCanChange bool `tl:"flag:1,encoded_in_bitflag"`
}

func (*AccountContentSettings) CRC() uint32 {
	return uint32(0x57e28221)
}

type AccountPassword struct {
	// flags position
	HasRecovery             bool                  `tl:"flag:0,encoded_in_bitflag"`
	HasSecureValues         bool                  `tl:"flag:1,encoded_in_bitflag"`
	HasPassword             bool                  `tl:"flag:2,encoded_in_bitflag"`
	CurrentAlgo             PasswordKdfAlgo       `tl:"flag:2"`
	SrpB                    []byte                `tl:"flag:2"`
	SrpId                   int64                 `tl:"flag:2"`
	Hint                    string                `tl:"flag:3"`
	EmailUnconfirmedPattern string                `tl:"flag:4"`
	NewAlgo                 PasswordKdfAlgo       `validate:"required"`
	NewSecureAlgo           SecurePasswordKdfAlgo `validate:"required"`
	SecureRandom            []byte                `validate:"required"`
}

func (*AccountPassword) CRC() uint32 {
	return uint32(0xad2641f8)
}

type AccountPasswordInputSettings struct {
	// flags position
	NewAlgo           PasswordKdfAlgo       `tl:"flag:0"`
	NewPasswordHash   []byte                `tl:"flag:0"`
	Hint              string                `tl:"flag:0"`
	Email             string                `tl:"flag:1"`
	NewSecureSettings *SecureSecretSettings `tl:"flag:2"`
}

func (*AccountPasswordInputSettings) CRC() uint32 {
	return uint32(0xc23727c9)
}

type AccountPasswordSettings struct {
	// flags position
	Email          string                `tl:"flag:0"`
	SecureSettings *SecureSecretSettings `tl:"flag:1"`
}

func (*AccountPasswordSettings) CRC() uint32 {
	return uint32(0x9a5c33e5)
}

type AccountPrivacyRules struct {
	Rules []PrivacyRule `validate:"required"`
	Chats []Chat        `validate:"required"`
	Users []User        `validate:"required"`
}

func (*AccountPrivacyRules) CRC() uint32 {
	return uint32(0x50a04e45)
}

type AccountSentEmailCode struct {
	EmailPattern string `validate:"required"`
	Length       int32  `validate:"required"`
}

func (*AccountSentEmailCode) CRC() uint32 {
	return uint32(0x811f854f)
}

type AccountTakeout struct {
	Id int64 `validate:"required"`
}

func (*AccountTakeout) CRC() uint32 {
	return uint32(0x4dba4501)
}

type AccountTmpPassword struct {
	TmpPassword []byte `validate:"required"`
	ValidUntil  int32  `validate:"required"`
}

func (*AccountTmpPassword) CRC() uint32 {
	return uint32(0xdb64fd34)
}

type AccountWebAuthorizations struct {
	Authorizations []*WebAuthorization `validate:"required"`
	Users          []User              `validate:"required"`
}

func (*AccountWebAuthorizations) CRC() uint32 {
	return uint32(0xed56c9fc)
}

type AccountDaysTTL struct {
	Days int32 `validate:"required"`
}

func (*AccountDaysTTL) CRC() uint32 {
	return uint32(0xb8d0afdf)
}

type AuthExportedAuthorization struct {
	Id    int32  `validate:"required"`
	Bytes []byte `validate:"required"`
}

func (*AuthExportedAuthorization) CRC() uint32 {
	return uint32(0xdf969c2d)
}

type AuthPasswordRecovery struct {
	EmailPattern string `validate:"required"`
}

func (*AuthPasswordRecovery) CRC() uint32 {
	return uint32(0x137948a5)
}

type AuthSentCode struct {
	// flags position
	Type          AuthSentCodeType `validate:"required"`
	PhoneCodeHash string           `validate:"required"`
	NextType      AuthCodeType     `tl:"flag:1"`
	Timeout       int32            `tl:"flag:2"`
}

func (*AuthSentCode) CRC() uint32 {
	return uint32(0x5e002502)
}

type Authorization struct {
	// flags position
	Current         bool   `tl:"flag:0,encoded_in_bitflag"`
	OfficialApp     bool   `tl:"flag:1,encoded_in_bitflag"`
	PasswordPending bool   `tl:"flag:2,encoded_in_bitflag"`
	Hash            int64  `validate:"required"`
	DeviceModel     string `validate:"required"`
	Platform        string `validate:"required"`
	SystemVersion   string `validate:"required"`
	ApiId           int32  `validate:"required"`
	AppName         string `validate:"required"`
	AppVersion      string `validate:"required"`
	DateCreated     int32  `validate:"required"`
	DateActive      int32  `validate:"required"`
	Ip              string `validate:"required"`
	Country         string `validate:"required"`
	Region          string `validate:"required"`
}

func (*Authorization) CRC() uint32 {
	return uint32(0xad01d61d)
}

type AutoDownloadSettings struct {
	// flags position
	Disabled              bool  `tl:"flag:0,encoded_in_bitflag"`
	VideoPreloadLarge     bool  `tl:"flag:1,encoded_in_bitflag"`
	AudioPreloadNext      bool  `tl:"flag:2,encoded_in_bitflag"`
	PhonecallsLessData    bool  `tl:"flag:3,encoded_in_bitflag"`
	PhotoSizeMax          int32 `validate:"required"`
	VideoSizeMax          int32 `validate:"required"`
	FileSizeMax           int32 `validate:"required"`
	VideoUploadMaxbitrate int32 `validate:"required"`
}

func (*AutoDownloadSettings) CRC() uint32 {
	return uint32(0xe04232f3)
}

type BankCardOpenUrl struct {
	Url  string `validate:"required"`
	Name string `validate:"required"`
}

func (*BankCardOpenUrl) CRC() uint32 {
	return uint32(0xf568028a)
}

type BotCommand struct {
	Command     string `validate:"required"`
	Description string `validate:"required"`
}

func (*BotCommand) CRC() uint32 {
	return uint32(0xc27ac8c7)
}

type BotInfo struct {
	UserId      int32         `validate:"required"`
	Description string        `validate:"required"`
	Commands    []*BotCommand `validate:"required"`
}

func (*BotInfo) CRC() uint32 {
	return uint32(0x98e81d3a)
}

type CdnConfig struct {
	PublicKeys []*CdnPublicKey `validate:"required"`
}

func (*CdnConfig) CRC() uint32 {
	return uint32(0x5725e40a)
}

type CdnPublicKey struct {
	DcId      int32  `validate:"required"`
	PublicKey string `validate:"required"`
}

func (*CdnPublicKey) CRC() uint32 {
	return uint32(0xc982eaba)
}

type ChannelAdminLogEvent struct {
	Id     int64                      `validate:"required"`
	Date   int32                      `validate:"required"`
	UserId int32                      `validate:"required"`
	Action ChannelAdminLogEventAction `validate:"required"`
}

func (*ChannelAdminLogEvent) CRC() uint32 {
	return uint32(0x3b5a3e40)
}

type ChannelAdminLogEventsFilter struct {
	// flags position
	Join     bool `tl:"flag:0,encoded_in_bitflag"`
	Leave    bool `tl:"flag:1,encoded_in_bitflag"`
	Invite   bool `tl:"flag:2,encoded_in_bitflag"`
	Ban      bool `tl:"flag:3,encoded_in_bitflag"`
	Unban    bool `tl:"flag:4,encoded_in_bitflag"`
	Kick     bool `tl:"flag:5,encoded_in_bitflag"`
	Unkick   bool `tl:"flag:6,encoded_in_bitflag"`
	Promote  bool `tl:"flag:7,encoded_in_bitflag"`
	Demote   bool `tl:"flag:8,encoded_in_bitflag"`
	Info     bool `tl:"flag:9,encoded_in_bitflag"`
	Settings bool `tl:"flag:10,encoded_in_bitflag"`
	Pinned   bool `tl:"flag:11,encoded_in_bitflag"`
	Edit     bool `tl:"flag:12,encoded_in_bitflag"`
	Delete   bool `tl:"flag:13,encoded_in_bitflag"`
}

func (*ChannelAdminLogEventsFilter) CRC() uint32 {
	return uint32(0xea107ae4)
}

type ChannelsAdminLogResults struct {
	Events []*ChannelAdminLogEvent `validate:"required"`
	Chats  []Chat                  `validate:"required"`
	Users  []User                  `validate:"required"`
}

func (*ChannelsAdminLogResults) CRC() uint32 {
	return uint32(0xed8af74d)
}

type ChannelsChannelParticipant struct {
	Participant ChannelParticipant `validate:"required"`
	Users       []User             `validate:"required"`
}

func (*ChannelsChannelParticipant) CRC() uint32 {
	return uint32(0xd0d9b163)
}

type ChatAdminRights struct {
	// flags position
	ChangeInfo     bool `tl:"flag:0,encoded_in_bitflag"`
	PostMessages   bool `tl:"flag:1,encoded_in_bitflag"`
	EditMessages   bool `tl:"flag:2,encoded_in_bitflag"`
	DeleteMessages bool `tl:"flag:3,encoded_in_bitflag"`
	BanUsers       bool `tl:"flag:4,encoded_in_bitflag"`
	InviteUsers    bool `tl:"flag:5,encoded_in_bitflag"`
	PinMessages    bool `tl:"flag:7,encoded_in_bitflag"`
	AddAdmins      bool `tl:"flag:9,encoded_in_bitflag"`
}

func (*ChatAdminRights) CRC() uint32 {
	return uint32(0x5fb224d5)
}

type ChatBannedRights struct {
	// flags position
	ViewMessages bool  `tl:"flag:0,encoded_in_bitflag"`
	SendMessages bool  `tl:"flag:1,encoded_in_bitflag"`
	SendMedia    bool  `tl:"flag:2,encoded_in_bitflag"`
	SendStickers bool  `tl:"flag:3,encoded_in_bitflag"`
	SendGifs     bool  `tl:"flag:4,encoded_in_bitflag"`
	SendGames    bool  `tl:"flag:5,encoded_in_bitflag"`
	SendInline   bool  `tl:"flag:6,encoded_in_bitflag"`
	EmbedLinks   bool  `tl:"flag:7,encoded_in_bitflag"`
	SendPolls    bool  `tl:"flag:8,encoded_in_bitflag"`
	ChangeInfo   bool  `tl:"flag:10,encoded_in_bitflag"`
	InviteUsers  bool  `tl:"flag:15,encoded_in_bitflag"`
	PinMessages  bool  `tl:"flag:17,encoded_in_bitflag"`
	UntilDate    int32 `validate:"required"`
}

func (*ChatBannedRights) CRC() uint32 {
	return uint32(0x9f120418)
}

type ChatOnlines struct {
	Onlines int32 `validate:"required"`
}

func (*ChatOnlines) CRC() uint32 {
	return uint32(0xf041e250)
}

type CodeSettings struct {
	// flags position
	AllowFlashcall bool `tl:"flag:0,encoded_in_bitflag"`
	CurrentNumber  bool `tl:"flag:1,encoded_in_bitflag"`
	AllowAppHash   bool `tl:"flag:4,encoded_in_bitflag"`
}

func (*CodeSettings) CRC() uint32 {
	return uint32(0xdebebe83)
}

type Config struct {
	// flags position
	PhonecallsEnabled       bool        `tl:"flag:1,encoded_in_bitflag"`
	DefaultP2PContacts      bool        `tl:"flag:3,encoded_in_bitflag"`
	PreloadFeaturedStickers bool        `tl:"flag:4,encoded_in_bitflag"`
	IgnorePhoneEntities     bool        `tl:"flag:5,encoded_in_bitflag"`
	RevokePmInbox           bool        `tl:"flag:6,encoded_in_bitflag"`
	BlockedMode             bool        `tl:"flag:8,encoded_in_bitflag"`
	PfsEnabled              bool        `tl:"flag:13,encoded_in_bitflag"`
	Date                    int32       `validate:"required"`
	Expires                 int32       `validate:"required"`
	TestMode                bool        `validate:"required"`
	ThisDc                  int32       `validate:"required"`
	DcOptions               []*DcOption `validate:"required"`
	DcTxtDomainName         string      `validate:"required"`
	ChatSizeMax             int32       `validate:"required"`
	MegagroupSizeMax        int32       `validate:"required"`
	ForwardedCountMax       int32       `validate:"required"`
	OnlineUpdatePeriodMs    int32       `validate:"required"`
	OfflineBlurTimeoutMs    int32       `validate:"required"`
	OfflineIdleTimeoutMs    int32       `validate:"required"`
	OnlineCloudTimeoutMs    int32       `validate:"required"`
	NotifyCloudDelayMs      int32       `validate:"required"`
	NotifyDefaultDelayMs    int32       `validate:"required"`
	PushChatPeriodMs        int32       `validate:"required"`
	PushChatLimit           int32       `validate:"required"`
	SavedGifsLimit          int32       `validate:"required"`
	EditTimeLimit           int32       `validate:"required"`
	RevokeTimeLimit         int32       `validate:"required"`
	RevokePmTimeLimit       int32       `validate:"required"`
	RatingEDecay            int32       `validate:"required"`
	StickersRecentLimit     int32       `validate:"required"`
	StickersFavedLimit      int32       `validate:"required"`
	ChannelsReadMediaPeriod int32       `validate:"required"`
	TmpSessions             int32       `tl:"flag:0"`
	PinnedDialogsCountMax   int32       `validate:"required"`
	PinnedInfolderCountMax  int32       `validate:"required"`
	CallReceiveTimeoutMs    int32       `validate:"required"`
	CallRingTimeoutMs       int32       `validate:"required"`
	CallConnectTimeoutMs    int32       `validate:"required"`
	CallPacketTimeoutMs     int32       `validate:"required"`
	MeUrlPrefix             string      `validate:"required"`
	AutoupdateUrlPrefix     string      `tl:"flag:7"`
	GifSearchUsername       string      `tl:"flag:9"`
	VenueSearchUsername     string      `tl:"flag:10"`
	ImgSearchUsername       string      `tl:"flag:11"`
	StaticMapsProvider      string      `tl:"flag:12"`
	CaptionLengthMax        int32       `validate:"required"`
	MessageLengthMax        int32       `validate:"required"`
	WebfileDcId             int32       `validate:"required"`
	SuggestedLangCode       string      `tl:"flag:2"`
	LangPackVersion         int32       `tl:"flag:2"`
	BaseLangPackVersion     int32       `tl:"flag:2"`
}

func (*Config) CRC() uint32 {
	return uint32(0x330b4067)
}

type Contact struct {
	UserId int32 `validate:"required"`
	Mutual bool  `validate:"required"`
}

func (*Contact) CRC() uint32 {
	return uint32(0xf911c994)
}

type ContactBlocked struct {
	UserId int32 `validate:"required"`
	Date   int32 `validate:"required"`
}

func (*ContactBlocked) CRC() uint32 {
	return uint32(0x561bc879)
}

type ContactStatus struct {
	UserId int32      `validate:"required"`
	Status UserStatus `validate:"required"`
}

func (*ContactStatus) CRC() uint32 {
	return uint32(0xd3680c61)
}

type ContactsFound struct {
	MyResults []Peer `validate:"required"`
	Results   []Peer `validate:"required"`
	Chats     []Chat `validate:"required"`
	Users     []User `validate:"required"`
}

func (*ContactsFound) CRC() uint32 {
	return uint32(0xb3134d9d)
}

type ContactsImportedContacts struct {
	Imported       []*ImportedContact `validate:"required"`
	PopularInvites []*PopularContact  `validate:"required"`
	RetryContacts  []int64            `validate:"required"`
	Users          []User             `validate:"required"`
}

func (*ContactsImportedContacts) CRC() uint32 {
	return uint32(0x77d01c3b)
}

type ContactsResolvedPeer struct {
	Peer  Peer   `validate:"required"`
	Chats []Chat `validate:"required"`
	Users []User `validate:"required"`
}

func (*ContactsResolvedPeer) CRC() uint32 {
	return uint32(0x7f077ad9)
}

type DataJSON struct {
	Data string `validate:"required"`
}

func (*DataJSON) CRC() uint32 {
	return uint32(0x7d748d04)
}

type DcOption struct {
	// flags position
	Ipv6      bool   `tl:"flag:0,encoded_in_bitflag"`
	MediaOnly bool   `tl:"flag:1,encoded_in_bitflag"`
	TcpoOnly  bool   `tl:"flag:2,encoded_in_bitflag"`
	Cdn       bool   `tl:"flag:3,encoded_in_bitflag"`
	Static    bool   `tl:"flag:4,encoded_in_bitflag"`
	Id        int32  `validate:"required"`
	IpAddress string `validate:"required"`
	Port      int32  `validate:"required"`
	Secret    []byte `tl:"flag:10"`
}

func (*DcOption) CRC() uint32 {
	return uint32(0x18b7a10d)
}

type DialogFilter struct {
	// flags position
	Contacts        bool        `tl:"flag:0,encoded_in_bitflag"`
	NonContacts     bool        `tl:"flag:1,encoded_in_bitflag"`
	Groups          bool        `tl:"flag:2,encoded_in_bitflag"`
	Broadcasts      bool        `tl:"flag:3,encoded_in_bitflag"`
	Bots            bool        `tl:"flag:4,encoded_in_bitflag"`
	ExcludeMuted    bool        `tl:"flag:11,encoded_in_bitflag"`
	ExcludeRead     bool        `tl:"flag:12,encoded_in_bitflag"`
	ExcludeArchived bool        `tl:"flag:13,encoded_in_bitflag"`
	Id              int32       `validate:"required"`
	Title           string      `validate:"required"`
	Emoticon        string      `tl:"flag:25"`
	PinnedPeers     []InputPeer `validate:"required"`
	IncludePeers    []InputPeer `validate:"required"`
	ExcludePeers    []InputPeer `validate:"required"`
}

func (*DialogFilter) CRC() uint32 {
	return uint32(0x7438f7e8)
}

type DialogFilterSuggested struct {
	Filter      *DialogFilter `validate:"required"`
	Description string        `validate:"required"`
}

func (*DialogFilterSuggested) CRC() uint32 {
	return uint32(0x77744d4a)
}

type EmojiKeywordsDifference struct {
	LangCode    string         `validate:"required"`
	FromVersion int32          `validate:"required"`
	Version     int32          `validate:"required"`
	Keywords    []EmojiKeyword `validate:"required"`
}

func (*EmojiKeywordsDifference) CRC() uint32 {
	return uint32(0x5cc761bd)
}

type EmojiLanguage struct {
	LangCode string `validate:"required"`
}

func (*EmojiLanguage) CRC() uint32 {
	return uint32(0xb3fb5361)
}

type EmojiURL struct {
	Url string `validate:"required"`
}

func (*EmojiURL) CRC() uint32 {
	return uint32(0xa575739d)
}

type Error struct {
	Code int32  `validate:"required"`
	Text string `validate:"required"`
}

func (*Error) CRC() uint32 {
	return uint32(0xc4b9f9bb)
}

type ExportedMessageLink struct {
	Link string `validate:"required"`
	Html string `validate:"required"`
}

func (*ExportedMessageLink) CRC() uint32 {
	return uint32(0x5dab1af4)
}

type FileHash struct {
	Offset int32  `validate:"required"`
	Limit  int32  `validate:"required"`
	Hash   []byte `validate:"required"`
}

func (*FileHash) CRC() uint32 {
	return uint32(0x6242c773)
}

type FileLocation struct {
	VolumeId int64 `validate:"required"`
	LocalId  int32 `validate:"required"`
}

func (*FileLocation) CRC() uint32 {
	return uint32(0xbc7fc6cd)
}

type Folder struct {
	// flags position
	AutofillNewBroadcasts     bool      `tl:"flag:0,encoded_in_bitflag"`
	AutofillPublicGroups      bool      `tl:"flag:1,encoded_in_bitflag"`
	AutofillNewCorrespondents bool      `tl:"flag:2,encoded_in_bitflag"`
	Id                        int32     `validate:"required"`
	Title                     string    `validate:"required"`
	Photo                     ChatPhoto `tl:"flag:3"`
}

func (*Folder) CRC() uint32 {
	return uint32(0xff544e65)
}

type FolderPeer struct {
	Peer     Peer  `validate:"required"`
	FolderId int32 `validate:"required"`
}

func (*FolderPeer) CRC() uint32 {
	return uint32(0xe9baa668)
}

type Game struct {
	// flags position
	Id          int64    `validate:"required"`
	AccessHash  int64    `validate:"required"`
	ShortName   string   `validate:"required"`
	Title       string   `validate:"required"`
	Description string   `validate:"required"`
	Photo       Photo    `validate:"required"`
	Document    Document `tl:"flag:0"`
}

func (*Game) CRC() uint32 {
	return uint32(0xbdf9653b)
}

type GlobalPrivacySettings struct {
	// flags position
	ArchiveAndMuteNewNoncontactPeers bool `tl:"flag:0"`
}

func (*GlobalPrivacySettings) CRC() uint32 {
	return uint32(0xbea2f424)
}

type HelpConfigSimple struct {
	Date    int32              `validate:"required"`
	Expires int32              `validate:"required"`
	Rules   []*AccessPointRule `validate:"required"`
}

func (*HelpConfigSimple) CRC() uint32 {
	return uint32(0x5a592a6c)
}

type HelpInviteText struct {
	Message string `validate:"required"`
}

func (*HelpInviteText) CRC() uint32 {
	return uint32(0x18cb9f78)
}

type HelpRecentMeUrls struct {
	Urls  []RecentMeUrl `validate:"required"`
	Chats []Chat        `validate:"required"`
	Users []User        `validate:"required"`
}

func (*HelpRecentMeUrls) CRC() uint32 {
	return uint32(0xe0310d7)
}

type HelpSupport struct {
	PhoneNumber string `validate:"required"`
	User        User   `validate:"required"`
}

func (*HelpSupport) CRC() uint32 {
	return uint32(0x17c6b5f6)
}

type HelpSupportName struct {
	Name string `validate:"required"`
}

func (*HelpSupportName) CRC() uint32 {
	return uint32(0x8c05f1c9)
}

type HelpTermsOfService struct {
	// flags position
	Popup         bool            `tl:"flag:0,encoded_in_bitflag"`
	Id            *DataJSON       `validate:"required"`
	Text          string          `validate:"required"`
	Entities      []MessageEntity `validate:"required"`
	MinAgeConfirm int32           `tl:"flag:1"`
}

func (*HelpTermsOfService) CRC() uint32 {
	return uint32(0x780a0310)
}

type HighScore struct {
	Pos    int32 `validate:"required"`
	UserId int32 `validate:"required"`
	Score  int32 `validate:"required"`
}

func (*HighScore) CRC() uint32 {
	return uint32(0x58fffcd0)
}

type ImportedContact struct {
	UserId   int32 `validate:"required"`
	ClientId int64 `validate:"required"`
}

func (*ImportedContact) CRC() uint32 {
	return uint32(0xd0028438)
}

type InlineBotSwitchPM struct {
	Text       string `validate:"required"`
	StartParam string `validate:"required"`
}

func (*InlineBotSwitchPM) CRC() uint32 {
	return uint32(0x3c20629f)
}

type InputAppEvent struct {
	Time float64   `validate:"required"`
	Type string    `validate:"required"`
	Peer int64     `validate:"required"`
	Data JSONValue `validate:"required"`
}

func (*InputAppEvent) CRC() uint32 {
	return uint32(0x1d1b1245)
}

type InputBotInlineMessageID struct {
	DcId       int32 `validate:"required"`
	Id         int64 `validate:"required"`
	AccessHash int64 `validate:"required"`
}

func (*InputBotInlineMessageID) CRC() uint32 {
	return uint32(0x890c3d89)
}

type InputClientProxy struct {
	Address string `validate:"required"`
	Port    int32  `validate:"required"`
}

func (*InputClientProxy) CRC() uint32 {
	return uint32(0x75588b3f)
}

type InputEncryptedChat struct {
	ChatId     int32 `validate:"required"`
	AccessHash int64 `validate:"required"`
}

func (*InputEncryptedChat) CRC() uint32 {
	return uint32(0xf141b5e1)
}

type InputFolderPeer struct {
	Peer     InputPeer `validate:"required"`
	FolderId int32     `validate:"required"`
}

func (*InputFolderPeer) CRC() uint32 {
	return uint32(0xfbd2c296)
}

type InputPeerNotifySettings struct {
	// flags position
	ShowPreviews bool   `tl:"flag:0"`
	Silent       bool   `tl:"flag:1"`
	MuteUntil    int32  `tl:"flag:2"`
	Sound        string `tl:"flag:3"`
}

func (*InputPeerNotifySettings) CRC() uint32 {
	return uint32(0x9c3d198e)
}

type InputPhoneCall struct {
	Id         int64 `validate:"required"`
	AccessHash int64 `validate:"required"`
}

func (*InputPhoneCall) CRC() uint32 {
	return uint32(0x1e36fded)
}

type InputContact struct {
	ClientId  int64  `validate:"required"`
	Phone     string `validate:"required"`
	FirstName string `validate:"required"`
	LastName  string `validate:"required"`
}

func (*InputContact) CRC() uint32 {
	return uint32(0xf392b7f4)
}

type InputSecureValue struct {
	// flags position
	Type        SecureValueType   `validate:"required"`
	Data        *SecureData       `tl:"flag:0"`
	FrontSide   InputSecureFile   `tl:"flag:1"`
	ReverseSide InputSecureFile   `tl:"flag:2"`
	Selfie      InputSecureFile   `tl:"flag:3"`
	Translation []InputSecureFile `tl:"flag:6"`
	Files       []InputSecureFile `tl:"flag:4"`
	PlainData   SecurePlainData   `tl:"flag:5"`
}

func (*InputSecureValue) CRC() uint32 {
	return uint32(0xdb21d0a7)
}

type InputSingleMedia struct {
	// flags position
	Media    InputMedia      `validate:"required"`
	RandomId int64           `validate:"required"`
	Message  string          `validate:"required"`
	Entities []MessageEntity `tl:"flag:0"`
}

func (*InputSingleMedia) CRC() uint32 {
	return uint32(0x1cc6e91f)
}

type InputStickerSetItem struct {
	// flags position
	Document   InputDocument `validate:"required"`
	Emoji      string        `validate:"required"`
	MaskCoords *MaskCoords   `tl:"flag:0"`
}

func (*InputStickerSetItem) CRC() uint32 {
	return uint32(0xffa0a496)
}

type InputThemeSettings struct {
	// flags position
	BaseTheme          BaseTheme          `validate:"required"`
	AccentColor        int32              `validate:"required"`
	MessageTopColor    int32              `tl:"flag:0"`
	MessageBottomColor int32              `tl:"flag:0"`
	Wallpaper          InputWallPaper     `tl:"flag:1"`
	WallpaperSettings  *WallPaperSettings `tl:"flag:1"`
}

func (*InputThemeSettings) CRC() uint32 {
	return uint32(0xbd507cd1)
}

type InputWebDocument struct {
	Url        string              `validate:"required"`
	Size       int32               `validate:"required"`
	MimeType   string              `validate:"required"`
	Attributes []DocumentAttribute `validate:"required"`
}

func (*InputWebDocument) CRC() uint32 {
	return uint32(0x9bed434d)
}

type Invoice struct {
	// flags position
	Test                     bool            `tl:"flag:0,encoded_in_bitflag"`
	NameRequested            bool            `tl:"flag:1,encoded_in_bitflag"`
	PhoneRequested           bool            `tl:"flag:2,encoded_in_bitflag"`
	EmailRequested           bool            `tl:"flag:3,encoded_in_bitflag"`
	ShippingAddressRequested bool            `tl:"flag:4,encoded_in_bitflag"`
	Flexible                 bool            `tl:"flag:5,encoded_in_bitflag"`
	PhoneToProvider          bool            `tl:"flag:6,encoded_in_bitflag"`
	EmailToProvider          bool            `tl:"flag:7,encoded_in_bitflag"`
	Currency                 string          `validate:"required"`
	Prices                   []*LabeledPrice `validate:"required"`
}

func (*Invoice) CRC() uint32 {
	return uint32(0xc30aa358)
}

type JSONObjectValue struct {
	Key   string    `validate:"required"`
	Value JSONValue `validate:"required"`
}

func (*JSONObjectValue) CRC() uint32 {
	return uint32(0xc0de1bd9)
}

type KeyboardButtonRow struct {
	Buttons []KeyboardButton `validate:"required"`
}

func (*KeyboardButtonRow) CRC() uint32 {
	return uint32(0x77608b83)
}

type LabeledPrice struct {
	Label  string `validate:"required"`
	Amount int64  `validate:"required"`
}

func (*LabeledPrice) CRC() uint32 {
	return uint32(0xcb296bf8)
}

type LangPackDifference struct {
	LangCode    string           `validate:"required"`
	FromVersion int32            `validate:"required"`
	Version     int32            `validate:"required"`
	Strings     []LangPackString `validate:"required"`
}

func (*LangPackDifference) CRC() uint32 {
	return uint32(0xf385c1f6)
}

type LangPackLanguage struct {
	// flags position
	Official        bool   `tl:"flag:0,encoded_in_bitflag"`
	Rtl             bool   `tl:"flag:2,encoded_in_bitflag"`
	Beta            bool   `tl:"flag:3,encoded_in_bitflag"`
	Name            string `validate:"required"`
	NativeName      string `validate:"required"`
	LangCode        string `validate:"required"`
	BaseLangCode    string `tl:"flag:1"`
	PluralCode      string `validate:"required"`
	StringsCount    int32  `validate:"required"`
	TranslatedCount int32  `validate:"required"`
	TranslationsUrl string `validate:"required"`
}

func (*LangPackLanguage) CRC() uint32 {
	return uint32(0xeeca5ce3)
}

type MaskCoords struct {
	N    int32   `validate:"required"`
	X    float64 `validate:"required"`
	Y    float64 `validate:"required"`
	Zoom float64 `validate:"required"`
}

func (*MaskCoords) CRC() uint32 {
	return uint32(0xaed6dbb2)
}

type MessageFwdHeader struct {
	// flags position
	FromId         int32  `tl:"flag:0"`
	FromName       string `tl:"flag:5"`
	Date           int32  `validate:"required"`
	ChannelId      int32  `tl:"flag:1"`
	ChannelPost    int32  `tl:"flag:2"`
	PostAuthor     string `tl:"flag:3"`
	SavedFromPeer  Peer   `tl:"flag:4"`
	SavedFromMsgId int32  `tl:"flag:4"`
	PsaType        string `tl:"flag:6"`
}

func (*MessageFwdHeader) CRC() uint32 {
	return uint32(0x353a686b)
}

type MessageInteractionCounters struct {
	MsgId    int32 `validate:"required"`
	Views    int32 `validate:"required"`
	Forwards int32 `validate:"required"`
}

func (*MessageInteractionCounters) CRC() uint32 {
	return uint32(0xad4fc9bd)
}

type MessageRange struct {
	MinId int32 `validate:"required"`
	MaxId int32 `validate:"required"`
}

func (*MessageRange) CRC() uint32 {
	return uint32(0xae30253)
}

type MessagesAffectedHistory struct {
	Pts      int32 `validate:"required"`
	PtsCount int32 `validate:"required"`
	Offset   int32 `validate:"required"`
}

func (*MessagesAffectedHistory) CRC() uint32 {
	return uint32(0xb45c69d1)
}

type MessagesAffectedMessages struct {
	Pts      int32 `validate:"required"`
	PtsCount int32 `validate:"required"`
}

func (*MessagesAffectedMessages) CRC() uint32 {
	return uint32(0x84d19185)
}

type MessagesArchivedStickers struct {
	Count int32               `validate:"required"`
	Sets  []StickerSetCovered `validate:"required"`
}

func (*MessagesArchivedStickers) CRC() uint32 {
	return uint32(0x4fcba9c8)
}

type MessagesBotCallbackAnswer struct {
	// flags position
	Alert     bool   `tl:"flag:1,encoded_in_bitflag"`
	HasUrl    bool   `tl:"flag:3,encoded_in_bitflag"`
	NativeUi  bool   `tl:"flag:4,encoded_in_bitflag"`
	Message   string `tl:"flag:0"`
	Url       string `tl:"flag:2"`
	CacheTime int32  `validate:"required"`
}

func (*MessagesBotCallbackAnswer) CRC() uint32 {
	return uint32(0x36585ea4)
}

type MessagesBotResults struct {
	// flags position
	Gallery    bool               `tl:"flag:0,encoded_in_bitflag"`
	QueryId    int64              `validate:"required"`
	NextOffset string             `tl:"flag:1"`
	SwitchPm   *InlineBotSwitchPM `tl:"flag:2"`
	Results    []BotInlineResult  `validate:"required"`
	CacheTime  int32              `validate:"required"`
	Users      []User             `validate:"required"`
}

func (*MessagesBotResults) CRC() uint32 {
	return uint32(0x947ca848)
}

type MessagesChatFull struct {
	FullChat ChatFull `validate:"required"`
	Chats    []Chat   `validate:"required"`
	Users    []User   `validate:"required"`
}

func (*MessagesChatFull) CRC() uint32 {
	return uint32(0xe5d7d19c)
}

type MessagesHighScores struct {
	Scores []*HighScore `validate:"required"`
	Users  []User       `validate:"required"`
}

func (*MessagesHighScores) CRC() uint32 {
	return uint32(0x9a3bfd99)
}

type MessagesInactiveChats struct {
	Dates []int32 `validate:"required"`
	Chats []Chat  `validate:"required"`
	Users []User  `validate:"required"`
}

func (*MessagesInactiveChats) CRC() uint32 {
	return uint32(0xa927fec5)
}

type MessagesMessageEditData struct {
	// flags position
	Caption bool `tl:"flag:0,encoded_in_bitflag"`
}

func (*MessagesMessageEditData) CRC() uint32 {
	return uint32(0x26b5dde6)
}

type MessagesPeerDialogs struct {
	Dialogs  []Dialog      `validate:"required"`
	Messages []Message     `validate:"required"`
	Chats    []Chat        `validate:"required"`
	Users    []User        `validate:"required"`
	State    *UpdatesState `validate:"required"`
}

func (*MessagesPeerDialogs) CRC() uint32 {
	return uint32(0x3371c354)
}

type MessagesSearchCounter struct {
	// flags position
	Inexact bool           `tl:"flag:1,encoded_in_bitflag"`
	Filter  MessagesFilter `validate:"required"`
	Count   int32          `validate:"required"`
}

func (*MessagesSearchCounter) CRC() uint32 {
	return uint32(0xe844ebff)
}

type MessagesStickerSet struct {
	Set       *StickerSet    `validate:"required"`
	Packs     []*StickerPack `validate:"required"`
	Documents []Document     `validate:"required"`
}

func (*MessagesStickerSet) CRC() uint32 {
	return uint32(0xb60a24a6)
}

type MessagesVotesList struct {
	// flags position
	Count      int32             `validate:"required"`
	Votes      []MessageUserVote `validate:"required"`
	Users      []User            `validate:"required"`
	NextOffset string            `tl:"flag:0"`
}

func (*MessagesVotesList) CRC() uint32 {
	return uint32(0x823f649)
}

type NearestDc struct {
	Country   string `validate:"required"`
	ThisDc    int32  `validate:"required"`
	NearestDc int32  `validate:"required"`
}

func (*NearestDc) CRC() uint32 {
	return uint32(0x8e1a1775)
}

type Page struct {
	// flags position
	Part      bool        `tl:"flag:0,encoded_in_bitflag"`
	Rtl       bool        `tl:"flag:1,encoded_in_bitflag"`
	V2        bool        `tl:"flag:2,encoded_in_bitflag"`
	Url       string      `validate:"required"`
	Blocks    []PageBlock `validate:"required"`
	Photos    []Photo     `validate:"required"`
	Documents []Document  `validate:"required"`
	Views     int32       `tl:"flag:3"`
}

func (*Page) CRC() uint32 {
	return uint32(0x98657f0d)
}

type PageCaption struct {
	Text   RichText `validate:"required"`
	Credit RichText `validate:"required"`
}

func (*PageCaption) CRC() uint32 {
	return uint32(0x6f747657)
}

type PageRelatedArticle struct {
	// flags position
	Url           string `validate:"required"`
	WebpageId     int64  `validate:"required"`
	Title         string `tl:"flag:0"`
	Description   string `tl:"flag:1"`
	PhotoId       int64  `tl:"flag:2"`
	Author        string `tl:"flag:3"`
	PublishedDate int32  `tl:"flag:4"`
}

func (*PageRelatedArticle) CRC() uint32 {
	return uint32(0xb390dc08)
}

type PageTableCell struct {
	// flags position
	Header       bool     `tl:"flag:0,encoded_in_bitflag"`
	AlignCenter  bool     `tl:"flag:3,encoded_in_bitflag"`
	AlignRight   bool     `tl:"flag:4,encoded_in_bitflag"`
	ValignMiddle bool     `tl:"flag:5,encoded_in_bitflag"`
	ValignBottom bool     `tl:"flag:6,encoded_in_bitflag"`
	Text         RichText `tl:"flag:7"`
	Colspan      int32    `tl:"flag:1"`
	Rowspan      int32    `tl:"flag:2"`
}

func (*PageTableCell) CRC() uint32 {
	return uint32(0x34566b6a)
}

type PageTableRow struct {
	Cells []*PageTableCell `validate:"required"`
}

func (*PageTableRow) CRC() uint32 {
	return uint32(0xe0c0c5e5)
}

type PaymentCharge struct {
	Id               string `validate:"required"`
	ProviderChargeId string `validate:"required"`
}

func (*PaymentCharge) CRC() uint32 {
	return uint32(0xea02c27e)
}

type PaymentRequestedInfo struct {
	// flags position
	Name            string       `tl:"flag:0"`
	Phone           string       `tl:"flag:1"`
	Email           string       `tl:"flag:2"`
	ShippingAddress *PostAddress `tl:"flag:3"`
}

func (*PaymentRequestedInfo) CRC() uint32 {
	return uint32(0x909c3f94)
}

type PaymentSavedCredentials struct {
	Id    string `validate:"required"`
	Title string `validate:"required"`
}

func (*PaymentSavedCredentials) CRC() uint32 {
	return uint32(0xcdc27a1f)
}

type PaymentsBankCardData struct {
	Title    string             `validate:"required"`
	OpenUrls []*BankCardOpenUrl `validate:"required"`
}

func (*PaymentsBankCardData) CRC() uint32 {
	return uint32(0x3e24e573)
}

type PaymentsPaymentForm struct {
	// flags position
	CanSaveCredentials bool                     `tl:"flag:2,encoded_in_bitflag"`
	PasswordMissing    bool                     `tl:"flag:3,encoded_in_bitflag"`
	BotId              int32                    `validate:"required"`
	Invoice            *Invoice                 `validate:"required"`
	ProviderId         int32                    `validate:"required"`
	Url                string                   `validate:"required"`
	NativeProvider     string                   `tl:"flag:4"`
	NativeParams       *DataJSON                `tl:"flag:4"`
	SavedInfo          *PaymentRequestedInfo    `tl:"flag:0"`
	SavedCredentials   *PaymentSavedCredentials `tl:"flag:1"`
	Users              []User                   `validate:"required"`
}

func (*PaymentsPaymentForm) CRC() uint32 {
	return uint32(0x3f56aea3)
}

type PaymentsPaymentReceipt struct {
	// flags position
	Date             int32                 `validate:"required"`
	BotId            int32                 `validate:"required"`
	Invoice          *Invoice              `validate:"required"`
	ProviderId       int32                 `validate:"required"`
	Info             *PaymentRequestedInfo `tl:"flag:0"`
	Shipping         *ShippingOption       `tl:"flag:1"`
	Currency         string                `validate:"required"`
	TotalAmount      int64                 `validate:"required"`
	CredentialsTitle string                `validate:"required"`
	Users            []User                `validate:"required"`
}

func (*PaymentsPaymentReceipt) CRC() uint32 {
	return uint32(0x500911e1)
}

type PaymentsSavedInfo struct {
	// flags position
	HasSavedCredentials bool                  `tl:"flag:1,encoded_in_bitflag"`
	SavedInfo           *PaymentRequestedInfo `tl:"flag:0"`
}

func (*PaymentsSavedInfo) CRC() uint32 {
	return uint32(0xfb8fe43c)
}

type PaymentsValidatedRequestedInfo struct {
	// flags position
	Id              string            `tl:"flag:0"`
	ShippingOptions []*ShippingOption `tl:"flag:1"`
}

func (*PaymentsValidatedRequestedInfo) CRC() uint32 {
	return uint32(0xd1451883)
}

type PeerNotifySettings struct {
	// flags position
	ShowPreviews bool   `tl:"flag:0"`
	Silent       bool   `tl:"flag:1"`
	MuteUntil    int32  `tl:"flag:2"`
	Sound        string `tl:"flag:3"`
}

func (*PeerNotifySettings) CRC() uint32 {
	return uint32(0xaf509d20)
}

type PeerSettings struct {
	// flags position
	ReportSpam            bool  `tl:"flag:0,encoded_in_bitflag"`
	AddContact            bool  `tl:"flag:1,encoded_in_bitflag"`
	BlockContact          bool  `tl:"flag:2,encoded_in_bitflag"`
	ShareContact          bool  `tl:"flag:3,encoded_in_bitflag"`
	NeedContactsException bool  `tl:"flag:4,encoded_in_bitflag"`
	ReportGeo             bool  `tl:"flag:5,encoded_in_bitflag"`
	Autoarchived          bool  `tl:"flag:7,encoded_in_bitflag"`
	GeoDistance           int32 `tl:"flag:6"`
}

func (*PeerSettings) CRC() uint32 {
	return uint32(0x733f2961)
}

type PhonePhoneCall struct {
	PhoneCall PhoneCall `validate:"required"`
	Users     []User    `validate:"required"`
}

func (*PhonePhoneCall) CRC() uint32 {
	return uint32(0xec82e140)
}

type PhoneCallProtocol struct {
	// flags position
	UdpP2P          bool     `tl:"flag:0,encoded_in_bitflag"`
	UdpReflector    bool     `tl:"flag:1,encoded_in_bitflag"`
	MinLayer        int32    `validate:"required"`
	MaxLayer        int32    `validate:"required"`
	LibraryVersions []string `validate:"required"`
}

func (*PhoneCallProtocol) CRC() uint32 {
	return uint32(0xfc878fc8)
}

type PhotosPhoto struct {
	Photo Photo  `validate:"required"`
	Users []User `validate:"required"`
}

func (*PhotosPhoto) CRC() uint32 {
	return uint32(0x20212ca8)
}

type Poll struct {
	Id int64 `validate:"required"`
	// flags position
	Closed         bool          `tl:"flag:0,encoded_in_bitflag"`
	PublicVoters   bool          `tl:"flag:1,encoded_in_bitflag"`
	MultipleChoice bool          `tl:"flag:2,encoded_in_bitflag"`
	Quiz           bool          `tl:"flag:3,encoded_in_bitflag"`
	Question       string        `validate:"required"`
	Answers        []*PollAnswer `validate:"required"`
	ClosePeriod    int32         `tl:"flag:4"`
	CloseDate      int32         `tl:"flag:5"`
}

func (*Poll) CRC() uint32 {
	return uint32(0x86e18161)
}

type PollAnswer struct {
	Text   string `validate:"required"`
	Option []byte `validate:"required"`
}

func (*PollAnswer) CRC() uint32 {
	return uint32(0x6ca9c2e9)
}

type PollAnswerVoters struct {
	// flags position
	Chosen  bool   `tl:"flag:0,encoded_in_bitflag"`
	Correct bool   `tl:"flag:1,encoded_in_bitflag"`
	Option  []byte `validate:"required"`
	Voters  int32  `validate:"required"`
}

func (*PollAnswerVoters) CRC() uint32 {
	return uint32(0x3b6ddad2)
}

type PollResults struct {
	// flags position
	Min              bool                `tl:"flag:0,encoded_in_bitflag"`
	Results          []*PollAnswerVoters `tl:"flag:1"`
	TotalVoters      int32               `tl:"flag:2"`
	RecentVoters     []int32             `tl:"flag:3"`
	Solution         string              `tl:"flag:4"`
	SolutionEntities []MessageEntity     `tl:"flag:4"`
}

func (*PollResults) CRC() uint32 {
	return uint32(0xbadcc1a3)
}

type PopularContact struct {
	ClientId  int64 `validate:"required"`
	Importers int32 `validate:"required"`
}

func (*PopularContact) CRC() uint32 {
	return uint32(0x5ce14175)
}

type PostAddress struct {
	StreetLine1 string `validate:"required"`
	StreetLine2 string `validate:"required"`
	City        string `validate:"required"`
	State       string `validate:"required"`
	CountryIso2 string `validate:"required"`
	PostCode    string `validate:"required"`
}

func (*PostAddress) CRC() uint32 {
	return uint32(0x1e8caaeb)
}

type ReceivedNotifyMessage struct {
	Id    int32 `validate:"required"`
	Flags int32 `validate:"required"`
}

func (*ReceivedNotifyMessage) CRC() uint32 {
	return uint32(0xa384b779)
}

type RestrictionReason struct {
	Platform string `validate:"required"`
	Reason   string `validate:"required"`
	Text     string `validate:"required"`
}

func (*RestrictionReason) CRC() uint32 {
	return uint32(0xd072acb4)
}

type SavedContact struct {
	Phone     string `validate:"required"`
	FirstName string `validate:"required"`
	LastName  string `validate:"required"`
	Date      int32  `validate:"required"`
}

func (*SavedContact) CRC() uint32 {
	return uint32(0x1142bd56)
}

type SecureCredentialsEncrypted struct {
	Data   []byte `validate:"required"`
	Hash   []byte `validate:"required"`
	Secret []byte `validate:"required"`
}

func (*SecureCredentialsEncrypted) CRC() uint32 {
	return uint32(0x33f0ea47)
}

type SecureData struct {
	Data     []byte `validate:"required"`
	DataHash []byte `validate:"required"`
	Secret   []byte `validate:"required"`
}

func (*SecureData) CRC() uint32 {
	return uint32(0x8aeabec3)
}

type SecureSecretSettings struct {
	SecureAlgo     SecurePasswordKdfAlgo `validate:"required"`
	SecureSecret   []byte                `validate:"required"`
	SecureSecretId int64                 `validate:"required"`
}

func (*SecureSecretSettings) CRC() uint32 {
	return uint32(0x1527bcac)
}

type SecureValue struct {
	// flags position
	Type        SecureValueType `validate:"required"`
	Data        *SecureData     `tl:"flag:0"`
	FrontSide   SecureFile      `tl:"flag:1"`
	ReverseSide SecureFile      `tl:"flag:2"`
	Selfie      SecureFile      `tl:"flag:3"`
	Translation []SecureFile    `tl:"flag:6"`
	Files       []SecureFile    `tl:"flag:4"`
	PlainData   SecurePlainData `tl:"flag:5"`
	Hash        []byte          `validate:"required"`
}

func (*SecureValue) CRC() uint32 {
	return uint32(0x187fa0ca)
}

type SecureValueHash struct {
	Type SecureValueType `validate:"required"`
	Hash []byte          `validate:"required"`
}

func (*SecureValueHash) CRC() uint32 {
	return uint32(0xed1ecdb0)
}

type ShippingOption struct {
	Id     string          `validate:"required"`
	Title  string          `validate:"required"`
	Prices []*LabeledPrice `validate:"required"`
}

func (*ShippingOption) CRC() uint32 {
	return uint32(0xb6213cdf)
}

type StatsBroadcastStats struct {
	Period                    *StatsDateRangeDays           `validate:"required"`
	Followers                 *StatsAbsValueAndPrev         `validate:"required"`
	ViewsPerPost              *StatsAbsValueAndPrev         `validate:"required"`
	SharesPerPost             *StatsAbsValueAndPrev         `validate:"required"`
	EnabledNotifications      *StatsPercentValue            `validate:"required"`
	GrowthGraph               StatsGraph                    `validate:"required"`
	FollowersGraph            StatsGraph                    `validate:"required"`
	MuteGraph                 StatsGraph                    `validate:"required"`
	TopHoursGraph             StatsGraph                    `validate:"required"`
	InteractionsGraph         StatsGraph                    `validate:"required"`
	IvInteractionsGraph       StatsGraph                    `validate:"required"`
	ViewsBySourceGraph        StatsGraph                    `validate:"required"`
	NewFollowersBySourceGraph StatsGraph                    `validate:"required"`
	LanguagesGraph            StatsGraph                    `validate:"required"`
	RecentMessageInteractions []*MessageInteractionCounters `validate:"required"`
}

func (*StatsBroadcastStats) CRC() uint32 {
	return uint32(0xbdf78394)
}

type StatsMegagroupStats struct {
	Period                  *StatsDateRangeDays     `validate:"required"`
	Members                 *StatsAbsValueAndPrev   `validate:"required"`
	Messages                *StatsAbsValueAndPrev   `validate:"required"`
	Viewers                 *StatsAbsValueAndPrev   `validate:"required"`
	Posters                 *StatsAbsValueAndPrev   `validate:"required"`
	GrowthGraph             StatsGraph              `validate:"required"`
	MembersGraph            StatsGraph              `validate:"required"`
	NewMembersBySourceGraph StatsGraph              `validate:"required"`
	LanguagesGraph          StatsGraph              `validate:"required"`
	MessagesGraph           StatsGraph              `validate:"required"`
	ActionsGraph            StatsGraph              `validate:"required"`
	TopHoursGraph           StatsGraph              `validate:"required"`
	WeekdaysGraph           StatsGraph              `validate:"required"`
	TopPosters              []*StatsGroupTopPoster  `validate:"required"`
	TopAdmins               []*StatsGroupTopAdmin   `validate:"required"`
	TopInviters             []*StatsGroupTopInviter `validate:"required"`
	Users                   []User                  `validate:"required"`
}

func (*StatsMegagroupStats) CRC() uint32 {
	return uint32(0xef7ff916)
}

type StatsAbsValueAndPrev struct {
	Current  float64 `validate:"required"`
	Previous float64 `validate:"required"`
}

func (*StatsAbsValueAndPrev) CRC() uint32 {
	return uint32(0xcb43acde)
}

type StatsDateRangeDays struct {
	MinDate int32 `validate:"required"`
	MaxDate int32 `validate:"required"`
}

func (*StatsDateRangeDays) CRC() uint32 {
	return uint32(0xb637edaf)
}

type StatsGroupTopAdmin struct {
	UserId  int32 `validate:"required"`
	Deleted int32 `validate:"required"`
	Kicked  int32 `validate:"required"`
	Banned  int32 `validate:"required"`
}

func (*StatsGroupTopAdmin) CRC() uint32 {
	return uint32(0x6014f412)
}

type StatsGroupTopInviter struct {
	UserId      int32 `validate:"required"`
	Invitations int32 `validate:"required"`
}

func (*StatsGroupTopInviter) CRC() uint32 {
	return uint32(0x31962a4c)
}

type StatsGroupTopPoster struct {
	UserId   int32 `validate:"required"`
	Messages int32 `validate:"required"`
	AvgChars int32 `validate:"required"`
}

func (*StatsGroupTopPoster) CRC() uint32 {
	return uint32(0x18f3d0f7)
}

type StatsPercentValue struct {
	Part  float64 `validate:"required"`
	Total float64 `validate:"required"`
}

func (*StatsPercentValue) CRC() uint32 {
	return uint32(0xcbce2fe0)
}

type StatsURL struct {
	Url string `validate:"required"`
}

func (*StatsURL) CRC() uint32 {
	return uint32(0x47a971e0)
}

type StickerPack struct {
	Emoticon  string  `validate:"required"`
	Documents []int64 `validate:"required"`
}

func (*StickerPack) CRC() uint32 {
	return uint32(0x12b299d4)
}

type StickerSet struct {
	// flags position
	Archived      bool      `tl:"flag:1,encoded_in_bitflag"`
	Official      bool      `tl:"flag:2,encoded_in_bitflag"`
	Masks         bool      `tl:"flag:3,encoded_in_bitflag"`
	Animated      bool      `tl:"flag:5,encoded_in_bitflag"`
	InstalledDate int32     `tl:"flag:0"`
	Id            int64     `validate:"required"`
	AccessHash    int64     `validate:"required"`
	Title         string    `validate:"required"`
	ShortName     string    `validate:"required"`
	Thumb         PhotoSize `tl:"flag:4"`
	ThumbDcId     int32     `tl:"flag:4"`
	Count         int32     `validate:"required"`
	Hash          int32     `validate:"required"`
}

func (*StickerSet) CRC() uint32 {
	return uint32(0xeeb46f27)
}

type Theme struct {
	// flags position
	Creator       bool           `tl:"flag:0,encoded_in_bitflag"`
	Default       bool           `tl:"flag:1,encoded_in_bitflag"`
	Id            int64          `validate:"required"`
	AccessHash    int64          `validate:"required"`
	Slug          string         `validate:"required"`
	Title         string         `validate:"required"`
	Document      Document       `tl:"flag:2"`
	Settings      *ThemeSettings `tl:"flag:3"`
	InstallsCount int32          `validate:"required"`
}

func (*Theme) CRC() uint32 {
	return uint32(0x28f1114)
}

type ThemeSettings struct {
	// flags position
	BaseTheme          BaseTheme `validate:"required"`
	AccentColor        int32     `validate:"required"`
	MessageTopColor    int32     `tl:"flag:0"`
	MessageBottomColor int32     `tl:"flag:0"`
	Wallpaper          WallPaper `tl:"flag:1"`
}

func (*ThemeSettings) CRC() uint32 {
	return uint32(0x9c14984a)
}

type TopPeer struct {
	Peer   Peer    `validate:"required"`
	Rating float64 `validate:"required"`
}

func (*TopPeer) CRC() uint32 {
	return uint32(0xedcdc05b)
}

type TopPeerCategoryPeers struct {
	Category TopPeerCategory `validate:"required"`
	Count    int32           `validate:"required"`
	Peers    []*TopPeer      `validate:"required"`
}

func (*TopPeerCategoryPeers) CRC() uint32 {
	return uint32(0xfb834291)
}

type UpdatesState struct {
	Pts         int32 `validate:"required"`
	Qts         int32 `validate:"required"`
	Date        int32 `validate:"required"`
	Seq         int32 `validate:"required"`
	UnreadCount int32 `validate:"required"`
}

func (*UpdatesState) CRC() uint32 {
	return uint32(0xa56c2a3e)
}

type UploadWebFile struct {
	Size     int32           `validate:"required"`
	MimeType string          `validate:"required"`
	FileType StorageFileType `validate:"required"`
	Mtime    int32           `validate:"required"`
	Bytes    []byte          `validate:"required"`
}

func (*UploadWebFile) CRC() uint32 {
	return uint32(0x21e753bc)
}

type UserFull struct {
	// flags position
	Blocked             bool                `tl:"flag:0,encoded_in_bitflag"`
	PhoneCallsAvailable bool                `tl:"flag:4,encoded_in_bitflag"`
	PhoneCallsPrivate   bool                `tl:"flag:5,encoded_in_bitflag"`
	CanPinMessage       bool                `tl:"flag:7,encoded_in_bitflag"`
	HasScheduled        bool                `tl:"flag:12,encoded_in_bitflag"`
	VideoCallsAvailable bool                `tl:"flag:13,encoded_in_bitflag"`
	User                User                `validate:"required"`
	About               string              `tl:"flag:1"`
	Settings            *PeerSettings       `validate:"required"`
	ProfilePhoto        Photo               `tl:"flag:2"`
	NotifySettings      *PeerNotifySettings `validate:"required"`
	BotInfo             *BotInfo            `tl:"flag:3"`
	PinnedMsgId         int32               `tl:"flag:6"`
	CommonChatsCount    int32               `validate:"required"`
	FolderId            int32               `tl:"flag:11"`
}

func (*UserFull) CRC() uint32 {
	return uint32(0xedf17c12)
}

type VideoSize struct {
	// flags position
	Type         string        `validate:"required"`
	Location     *FileLocation `validate:"required"`
	W            int32         `validate:"required"`
	H            int32         `validate:"required"`
	Size         int32         `validate:"required"`
	VideoStartTs float64       `tl:"flag:0"`
}

func (*VideoSize) CRC() uint32 {
	return uint32(0xe831c556)
}

type WallPaperSettings struct {
	// flags position
	Blur                  bool  `tl:"flag:1,encoded_in_bitflag"`
	Motion                bool  `tl:"flag:2,encoded_in_bitflag"`
	BackgroundColor       int32 `tl:"flag:0"`
	SecondBackgroundColor int32 `tl:"flag:4"`
	Intensity             int32 `tl:"flag:3"`
	Rotation              int32 `tl:"flag:4"`
}

func (*WallPaperSettings) CRC() uint32 {
	return uint32(0x5086cf8)
}

type WebAuthorization struct {
	Hash        int64  `validate:"required"`
	BotId       int32  `validate:"required"`
	Domain      string `validate:"required"`
	Browser     string `validate:"required"`
	Platform    string `validate:"required"`
	DateCreated int32  `validate:"required"`
	DateActive  int32  `validate:"required"`
	Ip          string `validate:"required"`
	Region      string `validate:"required"`
}

func (*WebAuthorization) CRC() uint32 {
	return uint32(0xcac943f2)
}

type WebPageAttribute struct {
	// flags position
	Documents []Document     `tl:"flag:0"`
	Settings  *ThemeSettings `tl:"flag:1"`
}

func (*WebPageAttribute) CRC() uint32 {
	return uint32(0x54b56617)
}
